root: true
env:
  browser: true
  es2021: true
  node: true

extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@stylistic/recommended

plugins:
  - react

parserOptions:
  ecmaVersion: latest
  sourceType: module

ignorePatterns:
  - node_modules/
  - dist/
  - .git/
  - .eslintcache

rules:
  react/prop-types: off
  react/react-in-jsx-scope: off
  react/jsx-uses-react: off
